### ISSUE TITLE
AbstractNumberPopupFilter the variables are Integer and not Number

### ISSUE THREAD

**Issue by juanetec** [Servoy/svyPopupFilter#19]
Hi,
in the forms.AbstractNumberPopupFilter the variables exactValue, minValue, maxValue, between1 and between2 are Integer.
Shouldn't you be numeric?

Un Saludo

Juan Ramírez

**Comment by paronne** [comment]
Hi Juan,

the Number filter it can actually be used for both INTEGER and NUMBER filter values.
I am considering changing these to NUMBER and introduce a new svyIntegerPopupFilter with same look & feel.

Regards,
Paolo

**Comment by juanetec** [comment]
Hi Paolo,
you cannot use Numeric if you write on the form.AbstractNumberPopupFilter any number with decimals, even changing the format from the form it desapears. The reason is that the variables exactValue, minValue, maxValue, between1 and between2 are INTEGER.
Look at the /svyPopupFilter/forms/AbstractNumberPopupFilter.js

`/**
 * @protected
 * @type {Number}
 *
 * @properties={typeid:35,uuid:"64A38280-61B3-4E05-8D5E-171030DDE1C3",variableType:4}
 */
var exactValue = 0;`


The **variableType:4** is 4 that it mean INTEGER.

Un Saludo

Juan Ramírez

**Comment by paronne** [comment]
Hi Juan,

that's correct. What i mean changing the var type to number (variableType 8) doesn't fully solve the problem because a different format would be required for NUMBER and INTEGER filter type.
That's why i am considering to introduce a new filter type to differentiate NUMBER from INTEGER (different variableType & different format)

**Comment by paronne** [comment]
Resolved as part of : https://support.servoy.com/browse/SVYX-62
