### ISSUE TITLE
Custom templates doesn't work in v 2.0.0

### ISSUE THREAD

**Issue by juanetec** [Servoy/svyPopupFilter#32]
Hi,
I have install the new servoy version (12.2020) and I have update the latest svyPopupfilter version and my custom templates that y have from the older version doesn't work. 
I use that for changing the language. 
It have been working in my other servoy version (06.2020) ant its works.
I have extend the new form svyCheckPopupFilter to my new form forms.nav_svyCheckPopupFilter.
I change the "YES" to "SI".
I put the on the popUpFilterLoadConfig the config line below and it does not work. :
scopes.svyToolbarFilter.setPopupRendererForm(scopes.svyToolbarFilter.FILTER_TYPES.CHECK, forms.nav_svyCheckPopupFilter);

Un Saludo

Juan Ramírez

**Comment by paronne** [comment]
Hi Juan,

I have created related case to this issue in our support.servoy.com.
You can track the progress at https://support.servoy.com/browse/SVYX-161

**Comment by paronne** [comment]
Hi Juan,

have you seen my comment at https://support.servoy.com/browse/SVYX-161 ?

I have realized there is no problem in using the custom template. You don't see your translated message because of the added logic from feature (https://github.com/Servoy/svyPopupFilter/wiki#new-locale)
Code in the base template overrides the texts with the new LOCALE value.
You can now make use of the Locale and, unless you have other customizations, get rid off your custom templates.

**Comment by juanetec** [comment]
Hi Paolo,
yes I found what you say and I solve it with the new locale.

Un Saludo
